const arr2=[
    {
        id:7,
        name:'Vishal Kriplani',
        position:'Software Engineering Intern at Fivetran',
        description1:'The CPL helped me to maintain the speed and accuracy of problem-solving. Senior-Junior interaction was increased during these events. The Knowledge sessions were quite informative.',
        description2:'',
        linkedin:'https://www.linkedin.com/in/vishal-kriplani-a33181190/',
        image:'images/Vishal Kriplani.png',
    },
    {
        id:8,
        name:'Sudhanshu Bhogal',
        position:'SDE-T at Amazon',
        description1:'I took part in Coding Premier League and multiple Competitive Coding Streak contests organised by O(1) Coding Club.Before attending those events I was not able to solve even very simple',
        description2:'coding problems on Codechef and Codeforces but after receiving proper guidance on resources and improving thought process for solving problems by O(1) Coding Club, I improved a lot in few months. None of the interviews I gave had gone without solving a coding problem, so I would suggest to improve your competitive coding skill if you are not good in it and I would highly recommend to be part of O(1) Coding Club and take active participation in various contests and sessions organized by them.',
        linkedin:'https://in.linkedin.com/in/sudhanshu-bhogal',
        image:'images/Sudhanshu Bhogal.png',
    },
    {
        id:9,
        name:'Yavar Vazir',
        position:'R&D intern at VMware',
        description1:'My preparation for Placements started with CPL organised by O(1) Coding Club.It was the best learning experience for me because it had coding problems of all levels, starting right f',
        description2:'rom basics and going up to difficult problems to be solved in 2.5 - 3 hours. It made a good habit of solving problems on daily basis and helped us to have a grip on competitive coding questions. As far as the interviews are concerned, the videos uploaded by O(1) were very helpful particular to each company, where they told us what exactly do they expect and how to prepare for it. I would recommend to anyone who is looking for mentorship, guidance about placements, go for O(1).',
        linkedin:'http://linkedin.com/in/yavar-vazir-a0843a182',
        image:'images/Yavar Vazir.png',
    },
    {
        id:10,
        name:'Rajat Bhanarkar',
        position:'Data Engineer Intern at Amazon',
        description1:'I attended the React.js workshop by O(1) Coding Club in Jan. It was a really informative, interactive and organized workshop.Everything was developed from scratch with proper stepwise explanation',
        description2:'.I would highly recommend O(1) Workshops.',
        linkedin:'https://www.linkedin.com/in/rajat-bhanarkar-11a859176',
        image:'images/Rajat Bhanarkar.png',
    },
    {
        id:11,
        name:'Nidhi Sharma',
        position:'SD Intern at Bank of New York Mellon',
        description1:'O(1) has guided us, gave us great tips for making resume and ways to crack off-campus opportunities',
        description2:'',
        linkedin:'https://www.linkedin.com/in/nidhivsharma10',
        image:'images/Nidhi Sharma.png',
    },
]
export default arr2;